Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using pesaulipo.Models;
using pesaulipo.Repository;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Text.RegularExpressions;

namespace pesaulipo.Controllers
{
    public class ReportsController : Controller
    {
		[Authorize(Roles = "HQ, Administrator, Supervisor, CO, Agent")]
		public ActionResult ViewReport(Reports reports, int id = 94865132)
		{
			DateTime dateTime;
			//Reports report = new Reports();
			DateTime? nullable = null;
			DateTime? nullable1 = null;
			UserManager<ApplicationUser> userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
			ApplicationUser applicationUser = userManager.FindById<ApplicationUser, string>(base.User.Identity.GetUserId());
			
			AgencyBankingDBDataContextDataContext agencyBankingDBDataContext = new AgencyBankingDBDataContextDataContext();
			Reports report1 = new Reports();
			ApplicationUser applicationUserr = (new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()))).FindById<ApplicationUser, string>(base.User.Identity.GetUserId());

			DataHandler dataHandler = new DataHandler();
			
			
			
			if (id != 94865132)
			{
				int num = id * -1;
				dateTime = DateTime.Now;
				nullable = new DateTime?(dateTime.AddDays((double)num));
			}
			
			string str3 = "";
			//string str4 = "Anonymous";
			if (base.User.IsInRole("Supervisor"))
			{
				str3 = "Supervisor";
			}
		
			else if (base.User.IsInRole("HQ"))
			{
				str3 = "HQ";
				
			}
			else if (base.User.IsInRole("Administrator"))
			{
				str3 = "Administrator";
				
			}
			else if (base.User.IsInRole("Agent"))
			{
				str3 = "Agent";
		
			}
			else if (base.User.IsInRole("CO"))
			{
				str3 = "CO";

			}
			report1.ReportStorage = dataHandler.Reports(str3, nullable, nullable1, null, null, applicationUserr.AgentCode, applicationUserr.Region, applicationUserr.Factory);

			report1.AllSaccosBalanceEnquiryCoretecShare = 0;
			Reports allSaccosBalanceEnquiryCount = report1;
			allSaccosBalanceEnquiryCount.AllSaccosBalanceEnquiryCoretecShare = allSaccosBalanceEnquiryCount.ReportStorage.AllSaccosBalanceEnquiryCount * 5;
			report1.AllSaccosLoanRepaymentCoretecShare = 0;
			report1.AllSaccosMemberRegistrationCoretecShare = 0;
			Reports allSaccosMinistatementCount = report1;
			allSaccosMinistatementCount.AllSaccosMinistatementCoretecShare = allSaccosMinistatementCount.ReportStorage.AllSaccosMinistatementCount * 5;
			report1.AllSaccosTransactionsCoretecShare = 0;
			Reports particularSaccoWithdrawalCount1001000 = report1;
			particularSaccoWithdrawalCount1001000.AllSaccosMemberactivationCoretecShare = particularSaccoWithdrawalCount1001000.ReportStorage.ParticularSaccoMemberactivationCount1001000 * -25 + report1.ReportStorage.ParticularSaccoMemberactivationCount10013000 * -25 + report1.ReportStorage.ParticularSaccoMemberactivationCount30016000 * -25 + report1.ReportStorage.ParticularSaccoMemberactivationCount600110000 * -25 + report1.ReportStorage.ParticularSaccoMemberactivationCount1000015000 * -30 + report1.ReportStorage.ParticularSaccoMemberactivationCount1500125000 * -30;
			Reports particularSaccoDepositCount501000 = report1;
			particularSaccoDepositCount501000.AllSaccosLoanApplicationCoretecShare = particularSaccoDepositCount501000.ReportStorage.ParticularSaccoLoanApplicationCount501000 * 10 + report1.ReportStorage.ParticularSaccoLoanApplicationCount10003000 * 10 + report1.ReportStorage.ParticularSaccoLoanApplicationCount30006000 * 15 + report1.ReportStorage.ParticularSaccoLoanApplicationCount600010000 * 15 + report1.ReportStorage.ParticularSaccoLoanApplicationCount1000015000 * 15 + report1.ReportStorage.ParticularSaccoLoanApplicationCount2500050000 * 20 + report1.ReportStorage.ParticularSaccoLoanApplicationCount50000100000 * 30;
			return base.View(report1);
		}
	}
}

Views/Shared/DashBoardPartialHome.cshtml
  <div class="row">
    @*@if (User.IsInRole("HQ"))
    {
        <div class="col-md-5">
            <div style="background-color:#679a02; text-align:center;">
                <a class="small-box-footer" href="@Url.Action("indexLoans", "Transactions")" style="color:white">Loans Application<i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-md-2">

        </div>
        <div class="col-md-5">
            <div style="background-color:#679a02; text-align:center;">
                <a class="small-box-footer" href="@Url.Action("ViewRegistration", "Transactions")" style="color:white">Member Registration<i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
    }
    @if (User.IsInRole("Administrator"))
    {
        <div class="col-md-5">
            <div style="background-color:#679a02; text-align:center;">
                <a class="small-box-footer" href="@Url.Action("indexLoans", "Transactions")" style="color:white">Loans Application<i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-md-2">

        </div>
        <div class="col-md-5">
            <div style="background-color:#679a02; text-align:center;">
                <a class="small-box-footer" href="@Url.Action("ViewRegistration", "Transactions")" style="color:white">Member Registration<i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
    }*@
</div>

    <br />

    <div class="row">
        @if (User.IsInRole("HQ"))
        {
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>@Model.AgentCount</h3>
                        <p>All Agents</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a class="small-box-footer" href="@Url.Action("GetAgentsList", "Dashboard")">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        }
        @if (User.IsInRole("Administrator"))
        {
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>@Model.AgentCount</h3>
                        <p>All Agents</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a class="small-box-footer" href="@Url.Action("GetAgentsList", "Dashboard")">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        }

        @if (User.IsInRole("Supervisor"))
        {
            @*<div class="col-lg-3 col-xs-6">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>@Model.AgentCount</h3>
                        <p>All Agents</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a class="small-box-footer" href="@Url.Action("GetAgentsList", "Dashboard")">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>*@

            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>@Model.DeviceCount</h3>
                        <p>Our Devices</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a class="small-box-footer" href="@Url.Action("Index", "Device")">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        }

        @if (User.IsInRole("CO"))
        {
            @*<div class="col-lg-3 col-xs-6">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>@Model.AgentCount</h3>
                        <p>All Agents</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a class="small-box-footer" href="@Url.Action("GetAgentsList", "Dashboard")">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>*@

            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>@Model.DeviceCount</h3>
                        <p>Our Devices</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a class="small-box-footer" href="@Url.Action("Index", "Device")">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        }

        @if (User.IsInRole("Agent"))
        {
            <div class="col-lg-2 col-xs-6">


            </div>
        }

        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow-gradient" style="background-color:#679a02">
                <div class="inner">
                    @*<h3>53<sup style="font-size: 20px">%</sup></h3>*@
                    <h3><sup>@Model.SaccoTransactionCount</sup></h3>
                    <p>Monthly Transactions</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>

                <a class="small-box-footer" href="@Url.Action("index", "Transactions")">More info <i class="fa fa-arrow-circle-right"></i></a>

            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>@Model.SaccoTransactionWeeklyCount</h3>
                    <p>Weekly Transactions</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a class="small-box-footer" href="@Url.Action("index", "Transactions", new { id = 7 })">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow-gradient">
                <div class="inner">
                    <h3>@Model.SaccoTransactionDailyCount</h3>
                    <p>Daily Transactions</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a class="small-box-footer" href="@Url.Action("index", "Transactions", new { id = 1 })">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
    </div>

Views/Shared/Header.cshtml
@using pesaulipo.Models
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@{
    var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
    // Get the current logged in User and look up the user in ASP.NET Identity
    var currentUser = manager.FindById(User.Identity.GetUserId());
    string Name = "Guest";
    string usertype = "";
    string agentCode = "";
    if (currentUser != null)
    {
        Name = currentUser.Email;
        usertype = currentUser.UserType;
        agentCode = currentUser.AgentCode;
    }

}
<header class="main-header">
    <!-- Logo -->
    <a href="@Url.Action("Home", "Dashboard")" class="logo" style="background-color: #679a02">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>G</b>FL</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>@agentCode</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" style="background-color: #14420c">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button" style="background-color: #14420c">
            <span class="sr-only">Toggle navigation</span>

        </a>



        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <!-- Notifications: style can be found in dropdown.less -->
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="~/dist/img/user-160x160.jpg" class="user-image" alt="User Image">
                        <span class="hidden-xs">@Name</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header" style="background-color:#679a02">
                            <img src="~/dist/img/user-160x160.jpg" class="img-circle" alt="User Image">
                            <p>

                                @Name
                                @*<small>Member since @currentUser.</small>*@
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <!-- Menu Footer-->

                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="@Url.Action("Signout", "Account", new {@class="btn btn-default btn-flat"})" style="color:#14420c">Sign Out</a>
                            </div>
                            <div class="pull-right">
                                <a href="@Url.Action("Index", "Manage", new {@class="btn btn-default btn-flat"})" style="color:#14420c">Manage</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
            </ul>
        </div>
    </nav>
</header>


Views/Shared/SidebarHome.cshtml
@using pesaulipo.Models
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@{

    var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
    // Get the current logged in User and look up the user in ASP.NET Identity
    var currentUser = manager.FindById(User.Identity.GetUserId());
    string Name = "";// currentUser.Email;
    if (Name.Length > 21)
    {
        Name = currentUser.Email;
        Name = Name.Remove(19) + "...";
    }
}
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar" style="background-color: #14420c">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">

            @if (User.IsInRole("HQ") || User.IsInRole("Supervisor") || User.IsInRole("CO"))
            {

                <li class="@Html.IsSelected(controller: "Dashboard") treeview">
                    <a href="@Url.Action("Home", "Dashboard")" style="background:#14420c">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="@Html.IsSelected(action: "Home")" onmouseover="Color:#efef86"><a href="@Url.Action("Home", "Dashboard")" style="background:#679a02"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                    </ul>
                </li>


                <li class="@Html.IsSelected(controller: "Dashboard") treeview">
                    <a href="@Url.Action("GetAgentsList", "Dashboard")" style="background:#14420c">
                        <i class="fa fa-maxcdn"></i>
                        <span>Agent Management</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="@Html.IsSelected(action: "GetAgentsList")"><a href="@Url.Action("GetAgentsList", "Dashboard")" style="background:#679a02"><i class="fa fa-circle-o"></i>View All Agents</a></li>

                    </ul>
                </li>

                <li class="@Html.IsSelected(controller: "Transactions") treeview">
                    <a href="@Url.Action("ViewSaccoTransactions", "Transactions")" style="background:#14420c">
                        <i class="fa fa-credit-card"></i>
                        <span>Reports</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="@Html.IsSelected(action: "ViewReport")"><a href="@Url.Action("ViewReport", "Reports")" style="background:#679a02"><i class="fa fa-money"></i> Summary</a></li>
                        <li class="@Html.IsSelected(action: "index")"><a href="@Url.Action("index", "Transactions")" style="background:#679a02"><i class="fa fa-money"></i> All Transactions</a></li>
                    </ul>
                </li>

            }

            @if (User.IsInRole("Administrator"))
            {

                <li class="@Html.IsSelected(controller: "Dashboard") treeview">
                    <a href="@Url.Action("Home", "Dashboard")" style="background:#14420c">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="@Html.IsSelected(action: "Home")" onmouseover="Color:#efef86"><a href="@Url.Action("Home", "Dashboard")" style="background:#679a02"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                    </ul>
                </li>


                <li class="@Html.IsSelected(controller: "Dashboard") treeview">
                    <a href="@Url.Action("GetAgentsList", "Dashboard")" style="background:#14420c">
                        <i class="fa fa-maxcdn"></i>
                        <span>Agent Management</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="@Html.IsSelected(action: "GetAgentsList")"><a href="@Url.Action("GetAgentsList", "Dashboard")" style="background:#679a02"><i class="fa fa-circle-o"></i>View All Agents</a></li>

                    </ul>
                </li>

                <li class="@Html.IsSelected(controller: "Transactions") treeview">
                    <a href="@Url.Action("ViewSaccoTransactions", "Transactions")" style="background:#14420c">
                        <i class="fa fa-credit-card"></i>
                        <span>Reports</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">

                        <li class="@Html.IsSelected(action: "ViewReport")"><a href="@Url.Action("ViewReport", "Reports")" style="background:#679a02"><i class="fa fa-money"></i> Summary</a></li>
                        <li class="@Html.IsSelected(action: "index")"><a href="@Url.Action("index", "Transactions")" style="background:#679a02"><i class="fa fa-money"></i> All Transactions</a></li>
                    </ul>
                </li>


                <li class="@Html.IsSelected(controller: "Account") treeview">
                    <a href="@Url.Action("Register", "Account")" style="background:#14420c">
                        <i class="fa fa-users"></i>
                        <span>Users</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="@Html.IsSelected(action: "GetUsers")"><a href="@Url.Action("GetUsers", "Dashboard")" style="background:#679a02"><i class="fa fa-users"></i> View All Users</a></li>
                    </ul>
                </li>

                <li class="@Html.IsSelected(controller: "Device") treeview">
                    <a href="@Url.Action("Create", "Device")" style="background:#14420c">
                        <i class="fa fa-credit-card"></i>
                        <span>Device Management</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="@Html.IsSelected(action: "RegisterDevice")"><a href="@Url.Action("RegisterDevice", "Device")" style="background:#679a02"><i class="fa fa-maxcdn"></i> Create Device </a></li>
                        <li class="@Html.IsSelected(action: "Index")"><a href="@Url.Action("Index", "Device")" style="background:#679a02"><i class="fa fa-dashboard"></i>Our Devices </a></li>
                        <li class="@Html.IsSelected(action: "WizarviewAdministrator")" onmouseup="Color:#ffff"><a href="https://www.wizarview.cn" target="_blank" style="background:#679a02"><i class="fa fa-user-plus"></i>Wizarview Administrator</a></li>
                    </ul>
                </li>

                <li class="@Html.IsSelected(controller: "Dashboard") treeview">
                    <ul class="treeview-menu">
                        <li onmouseover="Color:#efef86"><a href="@Url.Action("GetPDF", "Dashboard")" style="background:#679a02"><i class="fa fa-dashboard"></i> Agent Statement</a></li>
                    </ul>

                </li>
            }

            @if (User.IsInRole("Agent"))
            {

                <li class="@Html.IsSelected(controller: "Dashboard") treeview">
                    <a href="@Url.Action("Home", "Dashboard")" style="background:#14420c">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="@Html.IsSelected(action: "Home")" onmouseover="Color:#efef86"><a href="@Url.Action("Home", "Dashboard")" style="background:#679a02"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                    </ul>
                </li>


                <li class="@Html.IsSelected(controller: "Transactions") treeview">
                    <a href="@Url.Action("ViewSaccoTransactions", "Transactions")" style="background:#14420c">
                        <i class="fa fa-credit-card"></i>
                        <span>Reports</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="@Html.IsSelected(action: "ViewReport")"><a href="@Url.Action("ViewReport", "Reports")" style="background:#679a02"><i class="fa fa-money"></i> Summary</a></li>
                        <li class="@Html.IsSelected(action: "index")"><a href="@Url.Action("index", "Transactions")" style="background:#679a02"><i class="fa fa-money"></i> All Transactions</a></li>
                    </ul>
                </li>


                //apa...

            }

</section>
    <!-- /.sidebar -->
</aside>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>