Models/DashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace pesaulipo.Models
{
    public class DashboardViewModel
    {

		public int AgencyCount
		{
			get;
			set;
		}

		public int AgentCount
		{
			get;
			set;
		}

		public int DeviceCount
		{
			get;
			set;
		}


		public int LoanApplicationCount
		{
			get;
			set;
		}

		

		public int OthersCount
		{
			get;
			set;
		}

		

		public int SaccoTransactionDailyCount
		{
			get;
			set;
		}

		public int SaccoTransactionWeeklyCount
		{
			get;
			set;
		}

		

		public int TransactionCount
		{
			get;
			set;
		}

		public int TransactionDaily
		{
			get;
			set;
		}

		public int Transactions100MinsAgo
		{
			get;
			set;
		}

		public int Transactions120MinsAgo
		{
			get;
			set;
		}

		public int Transactions140MinsAgo
		{
			get;
			set;
		}

		public int Transactions160MinsAgo
		{
			get;
			set;
		}

		public int Transactions180MinsAgo
		{
			get;
			set;
		}

		public int Transactions200MinsAgo
		{
			get;
			set;
		}

		public int Transactions20MinsAgo
		{
			get;
			set;
		}

		public int Transactions40MinsAgo
		{
			get;
			set;
		}

		public int Transactions60MinsAgo
		{
			get;
			set;
		}

		public int Transactions80MinsAgo
		{
			get;
			set;
		}

		public int TransactionWeeklyCount
		{
			get;
			set;
		}

	
		
		public int MemberRegCount
		{
			get;
			set;
		}
		public int SaccoTransactionCount
		{
			get;
			set;
		}

		public int openLoanApplication
		{
			get;
			set;
		}
		public int pendingLoanApplication
		{
			get;
			set;
		}
		public int approvedLoanApplication
		{
			get;
			set;
		}
		public int rejectedLoanApplication
		{
			get;
			set;
		}
	}
}

Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using pesaulipo.Models;
using pesaulipo.Repository;

namespace pesaulipo.Controllers
{

	public class DashboardController : Controller
	{

		//string maill;
		public ActionResult Home()
		{

			ApplicationUser applicationUser = (new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()))).FindById<ApplicationUser, string>(base.User.Identity.GetUserId());

			if (applicationUser == null)
			{
				return RedirectToAction("Login", "Account");
			}
			else
			{
				DashboardViewModel dashboardViewModel = (new DataHandler()).DashBoardFunctions(applicationUser.UserType, applicationUser.AgentCode, applicationUser.Region, applicationUser.Factory);
				return this.PartialView("Home", dashboardViewModel);
			}




		}

		[Authorize(Roles = "HQ, Administrator, Supervisor, CO")]
		public ActionResult GetAgentsList()
		{
			ApplicationUser applicationUser = (new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()))).FindById<ApplicationUser, string>(base.User.Identity.GetUserId());

			if (applicationUser == null)
			{
				return RedirectToAction("Login", "Account");
			}
			else
			{
				DataHandler dataHandler = new DataHandler();
				AgentViewModel agentViewModel = new AgentViewModel()
				{
					AgentsList = dataHandler.GetSaccoAgentsList(applicationUser.UserType, applicationUser.Region, applicationUser.Factory)
				};
				return base.View(agentViewModel);
			}

		}

		public ActionResult GetUsers(string message = null)
		{
			if (message != null)
			{
				((dynamic)base.ViewBag).Toast = message;
			}
			UsersModel usersModel = new UsersModel();
			DataHandler dataHandler = new DataHandler();
			ApplicationUser applicationUser = (new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()))).FindById<ApplicationUser, string>(base.User.Identity.GetUserId());

			if (applicationUser == null)
			{
				return RedirectToAction("Login", "Account");
			}
			else
			{
				//ViewBag.Message = applicationUser.AgentCode;
				return base.View(dataHandler.ViewAllUsers(applicationUser.AgentCode));
			}

		}

		public ActionResult DeleteUser(string Id)
		{
			if (!(new DataHandler()).DeleteUser(Id))
			{
				return base.Content("Error");
			}
			return base.RedirectToAction("GetUsers", "Dashboard");
		}

		[Authorize(Roles = "Administrator")]
		public ActionResult SwitchUser(string agent_code)
		{
			if (agent_code != null)
			{
				AspNetUser myobject = new AspNetUser();
				myobject.AgentCode = agent_code;
				return base.View(myobject);
			}
			return base.View("Error");

		}

		[HttpPost]
		[Authorize(Roles = "Administrator")]
		public ActionResult SwitchUser(AspNetUser model)
		{
			if (!ModelState.IsValid)
			{
				RedirectToAction("Home");
			}

			using (AgencyBankingDBDataContextDataContext db = new AgencyBankingDBDataContextDataContext())
			{
				AspNetUser userr = db.AspNetUsers.Where(a => a.AgentCode == model.AgentCode).FirstOrDefault();
				if (userr != null)
				{
					//userr.UserType = model.UserType;
					//userr.Region = model.Region;
					//userr.Factory = model.Factory;
					userr.Enabled = model.Enabled;
					db.SubmitChanges();
				}
			}
			return RedirectToAction("GetUsers", "Dashboard");
		}


		[Authorize(Roles = "Administrator")]
		public ActionResult EditUser(string agent_code)
		{
			if (agent_code != null)
			{
				AspNetUser myobject = new AspNetUser();
				myobject.AgentCode = agent_code;
				return base.View(myobject);
			}
			return base.View("Error");

		}
		[HttpPost]
		[Authorize(Roles = "Administrator")]
		public ActionResult EditUser(AspNetUser model)
		{
			if (!ModelState.IsValid)
			{
				RedirectToAction("Home");
			}

			using (AgencyBankingDBDataContextDataContext db = new AgencyBankingDBDataContextDataContext())
			{
				AspNetUser userr = db.AspNetUsers.Where(a => a.AgentCode == model.AgentCode).FirstOrDefault();

				if (userr != null)
				{
					userr.UserType = model.UserType;
					userr.Region = model.Region;
					userr.Factory = model.Factory;

					db.SubmitChanges();
				}
			}

			return base.RedirectToAction("GetUsers", "Dashboard");
		}


		[Authorize(Roles = "Administrator")]
		public ActionResult EditSaccoAgent(string agent_code)
		{
			if (agent_code != null)
			{
				AgentViewModel myobject = new AgentViewModel();
				myobject.AgentCode = agent_code;
				return base.View(myobject);
			}
			return base.View("Error");

		}
		[HttpPost]
		[Authorize(Roles = "Administrator")]
		public ActionResult EditSaccoAgent(AgentViewModel model)
		{
			if (!ModelState.IsValid)
			{
				RedirectToAction("Home");
			}

			using (LiveDataDbContextDataContext db = new LiveDataDbContextDataContext())
			{
				GFL_Live_Agent_Application userr = db.GFL_Live_Agent_Applications.Where(a => a.Agent_Code == model.AgentCode).FirstOrDefault();
				if (userr != null)
				{
					userr.Agent_Code = model.AgentCode;
					userr.Email = model.Email;
					userr.Role = model.UserType;
					userr.RegionCode = model.Region;
					db.SubmitChanges();
				}
			}

			return base.RedirectToAction("GetAgentsList", "Dashboard");
		}

		public FileStreamResult GetPDF()
		{
			ApplicationUser applicationUser = (new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()))).FindById<ApplicationUser, string>(base.User.Identity.GetUserId());
			string agentstatementpath = WebServiceUrl.serviceDataObject.GetAgentStatement("GFL0185");
		    //string agentstatementpathh = "C:\\Users/Alex/Downloads/Documents/membersform.pdf";// WebServiceUrl.serviceDataObject.GetAgentStatement("GFL0185");

			 FileStream fs = new FileStream(agentstatementpath, FileMode.Open, FileAccess.Read);
			 //FileStream fss = new FileStream(agentstatementpathh, FileMode.Open, FileAccess.Read);

			 return File(fs, "application/pdf");
		}

	}
}

Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using pesaulipo.Models;
using pesaulipo.Repository;

namespace pesaulipo.Controllers
{
    public class RegionController : Controller
    {
        [HttpGet]
        [Authorize]
        public ActionResult GetRegisteredRegions(string mode = "default")
        {
            DataHandler dl = new DataHandler();

                    IEnumerable<Region> registeredRegionsRecordsForSelect = dl.GetRegions()
                      .OrderBy(c => c.Code)
                      .ToArray();
                    return Json(registeredRegionsRecordsForSelect, JsonRequestBehavior.AllowGet);
          
        }
    }
}

Views/Dashboard/AgentReport.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

Views/Dashboard/EditSaccoAgent.cshtml
@using pesaulipo.Models
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using System.Web;
@using System.Web.Mvc;
@model AgentViewModel
@{
    ViewBag.Title = "Update user";
    Layout = "~/Views/Shared/LayoutHome.cshtml";
}
<style>
    .createcombo {
        width: 50%;
    }
</style>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Update Agent</a></li>
        </ol>
    </section>
    <!-- Main content -->
    <br />
    <br />
    <section class="container">
        <div class="row">
            <!-- left column -->
            <div class="box box-warning">
                <div class="box-body">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                    <div class="form-horizontal col-lg-8 col-lg-offset-2">


                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.AgentCode, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.AgentCode, new { htmlAttributes = new { @class = "form-control"  } })
                               
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                               
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.UserType, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6" style="color:white">

                                @if (User.IsInRole("Administrator"))
                                {

                                    @Html.DropDownListFor(model => model.UserType,
                                        new List<SelectListItem>
                                            {
                                                new SelectListItem{ Text="Staff", Value = "HQ" },
                                                new SelectListItem{ Text="Administrator", Value = "Administrator" },
                                                new SelectListItem{ Text="Region Supervisor", Value = "Supervisor" },
                                                new SelectListItem{ Text="Factory CEO", Value = "CO" },
                                                new SelectListItem{ Text="Agent", Value = "Agent" },
                                            },
                                        new { @class = "form-control" })

                                }

                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">


                                @Html.DropDownListFor(model => model.Region,
                            Enumerable.Empty<SelectListItem>(),
                            "Select Region",
                            new { @class = "form-control", @id = "selectRegion" })

                            </div>
                        </div>

                        @*<div class="form-group">

                            @Html.LabelFor(model => model.Factory, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">


                                @Html.DropDownListFor(model => model.Factory,
                                    Enumerable.Empty<SelectListItem>(),
                                    "Select Factory",
                                    new { @class = "form-control", @id = "selectRegionFactory" })
                               
                            </div>
                        </div>*@


                        <div class="form-group">
                            <div class="col-md-6 col-lg-offset-3">
                                <button class="btn btn-primary btn-custom w-md waves-effect waves-light" type="submit">
                                    Update Agent
                                </button>
                            </div>
                        </div>

                    </div>

                    }
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @{
        string[] scriptFiles = {

        $"~/Scripts/myfiles/Registration.js"
        };
    }
    @Scripts.Render(scriptFiles)
    <script type="text/javascript">
  $(document).ready(function () {

      var selectRegionCode = '#selectRegion';
      var selectRegionFactoryId = '#selectRegionFactory';

      // 2. Load data for the select
      LoadRegionList("@Url.Action("GetRegisteredRegions", "Region")", selectRegionCode);
      // 3. Set up an event change listener
      // this sets the selected client name
      $(selectRegionCode).change(function () {
        if (!this.value) { ResetFactoryAndRole(selectRegionFactoryId); return; }
        //SetPlaceholderText('#selectedRegionPlaceholder', $(this).find(":selected").text());
        // Load the factories select with the selected region's factories
          LoadFactoriesList("@Url.Action("GetRegionFactory", "RegionFactory")", this.value, selectRegionFactoryId);
         // SetRegionFactories(this.value, selectRegionFactoryId);

      });
      // this sets the selected module name
      $(selectRegionFactoryId).change(function () {
        if (!this.value) return;
        SetPlaceholderText('#selectedFactoryPlaceholder', $(this).find(":selected").text());
      });
    });
    </script>
}


Views/Dashboard/EditUser.cshtml
@using pesaulipo.Models
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using System.Web;
@using System.Web.Mvc;
@model AspNetUser
@{
    ViewBag.Title = "Update user";
    Layout = "~/Views/Shared/LayoutHome.cshtml";
}
<style>
    .createcombo {
        width: 50%;
    }
</style>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Edit User</a></li>
        </ol>
    </section>
    <!-- Main content -->
    <br />
    <br />
    <section class="container">
        <div class="row">
            <!-- left column -->
            <div class="box box-warning">
                <div class="box-body">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal col-lg-8 col-lg-offset-2">


                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.AgentCode, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.AgentCode, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.AgentCode, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.UserType, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6" style="color:white">

                                    @if (User.IsInRole("Administrator"))
                                    {

                                        @Html.DropDownListFor(model => model.UserType,
                                            new List<SelectListItem>
                                                {
                                                    new SelectListItem{ Text="Staff", Value = "HQ" },
                                                    new SelectListItem{ Text="Administrator", Value = "Administrator" },
                                                    new SelectListItem{ Text="Region Supervisor", Value = "Supervisor" },
                                                    new SelectListItem{ Text="Factory CEO", Value = "CO" },
                                                    new SelectListItem{ Text="Agent", Value = "Agent" },
                                                },
                                            new { @class = "form-control" })

                                    }

                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">


                                    @Html.DropDownListFor(model => model.Region,
                                Enumerable.Empty<SelectListItem>(),
                                "Select Region",
                                new { @class = "form-control", @id = "selectRegion" })

                                </div>
                            </div>

                            <div class="form-group">

                                @Html.LabelFor(model => model.Factory, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">


                                    @Html.DropDownListFor(model => model.Factory,
                                        Enumerable.Empty<SelectListItem>(),
                                        "Select Factory",
                                        new { @class = "form-control", @id = "selectRegionFactory" })
                                    @Html.ValidationMessageFor(model => model.Factory, "", new { @class = "text-danger" })

                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-6 col-lg-offset-3">
                                    <button class="btn btn-primary btn-custom w-md waves-effect waves-light" type="submit">
                                        Update User
                                    </button>
                                </div>
                            </div>

                        </div>

                    }
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @{
        string[] scriptFiles = {

        $"~/Scripts/myfiles/Registration.js"
        };
    }
    @Scripts.Render(scriptFiles)
    <script type="text/javascript">
  $(document).ready(function () {

      var selectRegionCode = '#selectRegion';
      var selectRegionFactoryId = '#selectRegionFactory';

      // 2. Load data for the select
      LoadRegionList("@Url.Action("GetRegisteredRegions", "Region")", selectRegionCode);
      // 3. Set up an event change listener
      // this sets the selected client name
      $(selectRegionCode).change(function () {
        if (!this.value) { ResetFactoryAndRole(selectRegionFactoryId); return; }
        //SetPlaceholderText('#selectedRegionPlaceholder', $(this).find(":selected").text());
        // Load the factories select with the selected region's factories
          LoadFactoriesList("@Url.Action("GetRegionFactory", "RegionFactory")", this.value, selectRegionFactoryId);
         // SetRegionFactories(this.value, selectRegionFactoryId);

      });
      // this sets the selected module name
      $(selectRegionFactoryId).change(function () {
        if (!this.value) return;
        SetPlaceholderText('#selectedFactoryPlaceholder', $(this).find(":selected").text());
      });
    });
    </script>
}


Views/Dashboard/SwitchUser.cshtml
@using pesaulipo.Models
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using System.Web;
@using System.Web.Mvc;
@model AspNetUser
@{
    ViewBag.Title = "Update user";
    Layout = "~/Views/Shared/LayoutHome.cshtml";
}
<style>
    .createcombo {
        width: 50%;
    }
</style>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Disable User</a></li>
        </ol>
    </section>
    <!-- Main content -->
    <br />
    <br />
    <section class="container">
        <div class="row">
            <!-- left column -->
            <div class="box box-warning">
                <div class="box-body">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                    <div class="form-horizontal col-lg-8 col-lg-offset-2">


                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.AgentCode, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.AgentCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AgentCode, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                            @Html.LabelFor(model => model.UserType, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">

                                @Html.DropDownListFor(model => model.UserType,
                                    new List<SelectListItem>
                                        {
                                            new SelectListItem{ Text="Staff", Value = "HQ" },
                                            new SelectListItem{ Text="Administrator", Value = "Administrator" },
                                            new SelectListItem{ Text="Region Supervisor", Value = "Supervisor" },
                                            new SelectListItem{ Text="Factory CO", Value = "CO" },
                                            new SelectListItem{ Text="Agent", Value = "Agent" },
                                        },
                                    new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.DropDownListFor(model => model.Region,
                                         Enumerable.Empty<SelectListItem>(),
                                         "Select Region",
                                         new { @class = "form-control", @id = "selectRegion" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Factory, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.DropDownListFor(model => model.Factory,
                                                     Enumerable.Empty<SelectListItem>(),
                                                     "Select Factory",
                                                     new { @class = "form-control", @id = "selectRegionFactory" })
                                @Html.ValidationMessageFor(model => model.Factory, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.Enabled, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6" style="color:white">


                                @Html.DropDownListFor(model => model.Enabled,
                                    new List<SelectListItem>
                                        {
                                            new SelectListItem{ Text="Enable", Value = "true"  },
                                            new SelectListItem{ Text="Disable", Value = "false" },

                                        },
                                    new { @class = "form-control" })

                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-lg-offset-3">
                                <button class="btn btn-primary btn-custom w-md waves-effect waves-light" type="submit">
                                    Submit
                                </button>
                            </div>
                        </div>

                    </div>

                    }
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @{
        string[] scriptFiles = {

        $"~/Scripts/myfiles/Registration.js"
        };
    }
    @Scripts.Render(scriptFiles)
    <script type="text/javascript">
  $(document).ready(function () {

      var selectRegionCode = '#selectRegion';
      var selectRegionFactoryId = '#selectRegionFactory';

      // 2. Load data for the select
      LoadRegionList("@Url.Action("GetRegisteredRegions", "Region")", selectRegionCode);
      // 3. Set up an event change listener
      // this sets the selected client name
      $(selectRegionCode).change(function () {
        if (!this.value) { ResetFactoryAndRole(selectRegionFactoryId); return; }
        //SetPlaceholderText('#selectedRegionPlaceholder', $(this).find(":selected").text());
        // Load the factories select with the selected region's factories
          LoadFactoriesList("@Url.Action("GetRegionFactory", "RegionFactory")", this.value, selectRegionFactoryId);
         // SetRegionFactories(this.value, selectRegionFactoryId);

      });
      // this sets the selected module name
      $(selectRegionFactoryId).change(function () {
        if (!this.value) return;
        SetPlaceholderText('#selectedFactoryPlaceholder', $(this).find(":selected").text());
      });
    });
    </script>
}
